sudo: required
services:
  - docker

before_install:
  - docker build -t aistrate/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aistrate/react-test npm run test -- --coverage

after_success:
  - docker build -t aistrate/multi-client ./client
  - docker build -t aistrate/multi-nginx ./nginx
  - docker build -t aistrate/multi-server ./server
  - docker build -t aistrate/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aistrate/multi-client
  - docker push aistrate/multi-nginx
  - docker push aistrate/multi-server
  - docker push aistrate/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-441831299405
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY