sudo: required
services:
  - docker

before_install:
  - docker build -t aistrate/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true aistrate/react-test npm run test -- --coverage

after_success:
  - docker build -t aistrate/multi-client ./client
  - docker build -t aistrate/multi-nginx ./nginx
  - docker build -t aistrate/multi-server ./server
  - docker build -t aistrate/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aistrate/multi-client
  - docker push aistrate/multi-nginx
  - docker push aistrate/multi-server
  - docker push aistrate/multi-worker